apiVersion: v1
kind: Service
metadata:
  name: photo-app-service
  namespace: photo-app
spec:
  type: NodePort
  selector:
    app: photo-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
