apiVersion: v1
kind: ConfigMap
metadata:
  name: photo-app-config
  namespace: photo-app
data:
  FLASK_APP: "app.py"
  FLASK_DEBUG: "0"
  DB_HOST: "mysql"
  DB_NAME: "photo_portfolio"
  DB_PORT: "3306"
