apiVersion: apps/v1
kind: Deployment
metadata:
  name: photo-app
  namespace: photo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: photo-app
  template:
    metadata:
      labels:
        app: photo-app
    spec:
      containers:
      - name: web
        image: adityagaikwad6430/photo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              name: photo-app-config
              key: FLASK_APP

        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: photo-app-config
              key: FLASK_DEBUG

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: photo-app-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: photo-app-config
              key: DB_NAME

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: photo-app-config
              key: DB_PORT
              
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: EMAIL_USER

        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: EMAIL_PASS

        - name: FLASK_SECRET
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: FLASK_SECRET

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: DB_USER

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: my-app-secret
              key: DB_PASS