apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: photo-app
type: Opaque
data:
  EMAIL_USER: eWc3MDgzNzAwQGdtYWlsLmNvbQ==
  EMAIL_PASS: cG14dyBuaXhiIGNraHMgbmJoYg==
  FLASK_SECRET: cGFzcw==
  DB_USER: WUc=
  DB_PASS: cGFzcw==
